### PR TITLE
feat: Use backup directory, refact dockerfile

### PR DESCRIPTION
**Pull request by pratikbin**

### CODE REVIEW

**Comment by eeshugerman** [comment]
Hi, thanks for the PR!  #17 is a usecase I'm interested in supporting. But I can't accept this as is; there are far too many unnecessary, unrelated changes. If you provide a patch with minimal changes for #17, I will consider merging.

**Comment by pratikbin** [comment]
> If you provide a patch with minimal changes for https://github.com/eeshugerman/postgres-backup-s3/issues/17, I will consider merging.

There are

### Major

- Move `install.sh` to `dockerfile`
- Add `backup` directory in `backup.sh`

### Minor
- `chmod +x` both backup and restore file, since git preserve permissions

So if you want me to break down these changes in separate PR, then let me know

**Comment by pratikbin** [comment]
@eeshugerman  Any updates to get this merge ?

**Comment by eeshugerman** [comment]
Hi, sorry for the delay. Thanks for the breakdown of changes here.

I don't want to get rid of `install.sh` unless we have a good reason to, so I'm not going to merge this as-is.

If you open a separate PR with only the `backup/` directory changes, and another PR with only the `chmod +x` changes, I will likely merge them both.

**Pull request closed without merging**
