### PR TITLE
Add ARM64 Builds

### PR DESCRIPTION
**Pull request by cablespaghetti**
Hi,

Thanks for the super useful project.

I needed to get this working on an ARM64 kubernetes cluster, so here's my changes :)

### CODE REVIEW

**Comment by eeshugerman** [comment]
Hi, thanks for this! I intend to merge, just want to look into the go-cron fork and version diff first when I have a moment.

**Review by eeshugerman — CHANGES_REQUESTED** [review]
Looks good, just a couple minor changes/additions please.

It looks like the new go-cron fork is actively maintained, unlike what we used before, so that's nice. Here's the diff in case we run into any issues here: https://github.com/odise/go-cron/compare/v0.0.6...ivoronin:go-cron:v0.0.5

**Comment by cablespaghetti** [comment]
Fixed 👍

**Review by eeshugerman — APPROVED** [review]
💯 thanks again!

**Pull request merged**
